# ──────────────────────────────  PROMETHEUS STACK  ─────────────────────────────
alertmanager:
  enabled: true
  alertmanagerSpec:
    nodeSelector:
      nodegroup-type: backend
    receivers:
      - name: default
        email_configs:
          - to: "devops979@gmail.com"
  configMaps: []

prometheus:
  prometheusSpec:
    nodeSelector:
      nodegroup-type: backend

nodeExporter:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    eks.amazonaws.com/compute-type: ec2

# ───────────────────────────────  GRAFANA  ────────────────────────────────────
grafana:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

# ─────────────────────────────  SERVICEMONITORS  ──────────────────────────────
serviceMonitors:
  - name: backend-fargate
    selector:
      matchLabels:
        app: backend
    namespaceSelector:
      matchNames: ["backend"]
    endpoints:
      - port: http
        path: /metrics
        interval: 30s

  - name: frontend-fargate
    selector:
      matchLabels:
        app: frontend
    namespaceSelector:
      matchNames: ["frontend"]
    endpoints:
      - port: http
        path: /metrics
        interval: 30s
