# ────────────────────────────  PROMETHEUS STACK  ────────────────────────────
# Alertmanager enabled + pinned to *backend* node-group
alertmanager:
  enabled: true
  alertmanagerSpec:
    nodeSelector:
      nodegroup-type: backend               # ⟵ changed
    receivers:
      - name: default
        email_configs:
          - to: "devops979@gmail.com"
  configMaps: []                            # rules shipped separately

# Prometheus server pinned to *backend* node-group
prometheus:
  prometheusSpec:
    nodeSelector:
      nodegroup-type: backend               # ⟵ changed

# Node-exporter DaemonSet — run **only** on EC2
nodeExporter:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    eks.amazonaws.com/compute-type: "ec2"

# ────────────────────────────  SERVICEMONITORS  ─────────────────────────────
# Scrape your Fargate-based frontend / backend apps
serviceMonitors:
  - name: backend-fargate
    selector:
      matchLabels:
        app: backend
    namespaceSelector:
      matchNames: ["backend"]
    endpoints:
      - port: http
        path: /metrics
        interval: 30s

  - name: frontend-fargate
    selector:
      matchLabels:
        app: frontend
    namespaceSelector:
      matchNames: ["frontend"]
    endpoints:
      - port: http
        path: /metrics
        interval: 30s
