apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::<ACCOUNT_ID>:role/${cluster_name}-irsa-secrets
    spec:
      serviceAccountName: secrets-reader
      containers:
      - name: flask
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/flask-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        readinessProbe:
          httpGet:
            path: /api/employees
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  namespace: backend
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-backend
