name: Build & Deploy Apps

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # OIDC to assume role
      contents: read

    env:
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

    steps:
    - uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build & push Flask (backend)
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 211125325699.dkr.ecr.ap-south-1.amazonaws.com
        docker build -t flask-backend ./backend
        docker tag  flask-backend:latest $ECR_REGISTRY/support-portal-flask-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/support-portal-flask-backend:$IMAGE_TAG

    # ───────────────────────── 4. Build & push React ───────────────
    - name: Build & push React (frontend)
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 211125325699.dkr.ecr.ap-south-1.amazonaws.com
        docker build -t react-frontend ./frontend
        docker tag  react-frontend:latest $ECR_REGISTRY/support-portal-flask-frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/support-portal-flask-frontend:$IMAGE_TAG
      
    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.32.0'
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --name support-eks --region ap-south-1

    - name: Deploy manifests
      run: |
        # Create namespaces (idempotent)
        kubectl apply -f k8s/namespaces.yaml

        # Patch images with the new tag (no manifest edits needed)
        kubectl set image deployment/flask-backend  -n backend  \
          flask=$ECR_REGISTRY/support-portal-flask-backend:$IMAGE_TAG

        kubectl set image deployment/react-frontend -n frontend \
          react=$ECR_REGISTRY/support-portal-flask-frontend:$IMAGE_TAG

        # Ingress & any other static manifests
        kubectl apply -f k8s/ingress.yaml

